#pytest.ini - это файл конфигурации для фреймворка тестирования pytest.

[pytest]

markers =
   smoke: Быстрая проверка основных функций (Text Box, Alerts)
    critical: Критически важные тесты (Alerts)
    elements: Все тесты раздела Elements
    widgets: Тесты виджетов (Select Menu)
    alerts: Тесты всех типов алертов
    text_box: Тест формы Text Box
    upload: Тест загрузки файлов
    dynamic: Тест динамических свойств
    select_menu: Тест выпадающих списков
    mouse: Тест взаимодействия с мышью
    actions: Тест сложных действий пользователя

addopts =
    -sv
    --reruns=2
    --only-rerun TimeoutException
    --only-rerun HTTPSConnectionPool
    --only-rerun StaleElementReferenceException
    --only-rerun IФnvalidSessionIdException